
export default {
    

    GETTING_USERSYSTEM: 'GETTING_USERSYSTEM',
    GET_USERSYSTEM_SUCCESS: 'GET_USERSYSTEM_SUCCESS',
    GET_USERSYSTEM_FAILURE: 'GET_USERSYSTEM_FAILURE',
    UPDATTING_STATUS_USERSYSTEM: 'UPDATTING_STATUS_USERSYSTEM',
    CHANGE_STATUS_USERSYSTEM_SUCCESS: 'CHANGE_STATUS_USERSYSTEM_SUCCESS',
    CHANGE_STATUS_USERSYSTEM_FAILURE: 'CHANGE_STATUS_USERSYSTEM_FAILURE',
    ADD_USERSYSTEM: 'ADD_USERSYSTEM',
    ADD_USERSYSTEM_SUCCESS: 'ADD_USERSYSTEM_SUCCESS',
    ADD_USERSYSTEM_FAILURE: 'ADD_USERSYSTEM_FAILURE',
    UPDATE_USERSYSTEM: 'UPDATE_USERSYSTEM',
    UPDATE_USERSYSTEM_SUCCESS: 'UPDATE_USERSYSTEM_SUCCESS',
    UPDATE_USERSYSTEM_FAILURE: 'UPDATE_USERSYSTEM_FAILURE',
    DELETE_USERSYSTEM: 'DELETE_USERSYSTEM',
    DELETE_USERSYSTEM_SUCCESS: 'DELETE_USERSYSTEM_SUCCESS',
    DELETE_USERSYSTEM_FAILURE: 'DELETE_USERSYSTEM_FAILURE',



    GETTING_SHOP: 'GETTING_SHOP',
    GET_SHOP_SUCCESS: 'GET_SHOP_SUCCESS',
    GET_SHOP_FAILURE: 'GET_SHOP_FAILURE',
    UPDATTING_STATUS_SHOP: 'UPDATTING_STATUS_SHOP',
    CHANGE_STATUS_SHOP_SUCCESS: 'CHANGE_STATUS_SHOP_SUCCESS',
    CHANGE_STATUS_SHOP_FAILURE:'CHANGE_STATUS_SHOP_FAILURE',

    SET_OPEN_KEY: 'SET_OPEN_KEY',
    SET_PAGE: 'SET_PAGE',

    GETTING_REQUESTS: "GETTING_REQUESTS_SERVICESHOP",
    GET_REQUESTS_SUCCESS: "GET_REQUESTS_SUCCESS",
    GET_REQUESTS_FAILURE: "GET_REQUESTS_FAILURE",

    GETTING_SERVICESHOP: 'GETTING_SERVICESHOP',
    GET_SERVICESHOPS_SUCCESS: 'GET_SERVICESHOS_SUCCESS',
    GET_SERVICESHOPS_FAILURE: 'GET_SERVICESHOPS_FAILURE',
    GET_SERVICESHOP_SUCCESS: 'GET_SERVICESHOP_SUCCESS',
    GET_SERVICESHOP_FAILURE: 'GET_SERVICESHOP_FAILURE',
    ADD_SERVICESHOP_SUCCESS: 'ADD_SERVICESHOP_SUCCESS',
    ADD_SERVICESHOP_FAILURE: 'ADD_SERVICESHOP_FAILURE',
    UPDATTING_STATUS: 'UPDATTING_STATUS',
    CHANGE_STATUS_SUCCESS: 'CHANGE_STATUS_SUCCESS',
    CHANGE_STATUS_FAILURE: 'CHANGE_STATUS_FAILURE',


    UPDATTING_STATUS_SERVICESHOP : 'UPDATTING_STATUS_SERVICESHOP',
    CHANGE_STATUS_SERVICESHOP_SUCCESS: 'CHANGE_STATUS_SERVICESHOP_SUCCESS',
    CHANGE_STATUS_SERVICESHOP_FAILURE: 'CHANGE_STATUS_SERVICESHOP_FAILURE',

    AUTH_ACCOUNT_LOADING: 'AUTH_ACCOUNT_LOADING',
    AUTH_ACCOUNT_SUCCESS: 'AUTH_ACCOUNT_SUCCESS',
    AUTH_ACCOUNT_FAILURE: 'AUTH_ACCOUNT_FAILURE',
    AUTH_CHANGEPASSWORD_SUCCESS: 'AUTH_CHANGEPASSWORD_SUCCESS',
    AUTH_CHANGEPASSWORD_FAILURE: 'AUTH_CHANGEPASSWORD_FAILURE',

    AUTH_REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',
    AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCES',

    GETTING_USER: 'GETTING_USER',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_FAILURE: 'GET_USER_FAILURE',
    FINDBYID_USER: 'FINDBYID_USER',
    FINDBYID_USER_FAILURE: 'FINDBYID_USER_FAILURE',
    UPDATTING_STATUS_USER: 'UPDATTING_STATUS_USER',
    CHANGE_STATUS_USER_SUCCESS: 'CHANGE_STATUS_USER_SUCCESS',
    CHANGE_STATUS_USER_FAILURE: 'CHANGE_STATUS_USER_FAILURE',

    LOG_IN_FAILURE: 'LOG_IN_FAILURE',
    LOGGING_IN: 'LOGGING_IN',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_OUT: 'LOG_OUT',

    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR',

}
